<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\RadishDeck.Core\RadishDeck.Core.csproj" />
    <ProjectReference Include="..\RadishDeck.Infrastructure\RadishDeck.Infrastructure.csproj" />
    <Content Include="..\RadishDeck.SharedWeb\renderer.js" Link="wwwroot\shared\renderer.js" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="..\RadishDeck.SharedWeb\renderer.css" Link="wwwroot\shared\renderer.css" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
