<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>RadishDeck</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\RadishDeck.Core\RadishDeck.Core.csproj" />
  </ItemGroup>
</Project>
